#   Copyright 2020 The KNIX Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "nginx.fullname" . }}-nginx-conf"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.name" . | quote }}
    release: {{ .Release.Name | quote }}
data:
  mfn.conf: |-
    log_format mfn_log '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';

    server {
      listen 8080;
      client_max_body_size 100m;

      access_log /opt/mfn/nginx/access.log mfn_log;
      error_log /opt/mfn/nginx/error.log info;

      root /opt/mfn/nginx/gui;
      location / {
        alias /opt/mfn/nginx/gui/;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . | quote }}
  labels:
    app: {{ include "nginx.name" . | quote }}
    release: {{ .Release.Name | quote }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: {{ include "nginx.name" . | quote }}
    release: {{ .Release.Name | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx.name" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.nginx.Replicas }}
  selector:
    matchLabels:
        app: {{ include "nginx.name" . | quote }}
        release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.name" . | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: nginx
        image: "{{ .Values.imageRepo }}{{ .Values.nginx.imagePath }}:{{ .Values.nginx.imageTag }}"
        imagePullPolicy: "{{ .Values.nginx.imagePullPolicy }}"
        ports:
        - name: http
          containerPort: 8080
        resources:
{{ toYaml .Values.nginx.resources | indent 10}}
        volumeMounts:
        - name: conf-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: conf-volume
        configMap:
          name: "{{ template "nginx.fullname" . }}-nginx-conf"
