#   Copyright 2020 The KNIX Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: store-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: microfunctions-store
    release: {{ .Release.Name | quote }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 50000
  selector:
    app: microfunctions-store
    release: {{ .Release.Name | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: microfunctions-store
    release: {{ .Release.Name | quote }}
spec:
  selector:
    matchLabels:
        app: microfunctions-store
        release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: microfunctions-store
        release: {{ .Release.Name | quote }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: frontend
        image: "{{ .Values.imageRepo }}{{ .Values.nginx.frontendImagePath }}:{{ .Values.nginx.frontendImageTag }}"
        imagePullPolicy: "{{ .Values.nginx.imagePullPolicy }}"
        env:
        - name: HTTP_PORT
          value: "50000"
        - name: MFN_DATALAYER
          value: "datalayer.{{ .Release.Namespace }}.svc.cluster.local"
        ports:
        - containerPort: 50000
          name: http
        resources:
{{ toYaml .Values.nginx.frontendResources | indent 10}}